### ISSUE TITLE
[FEAT] Prisma support

### ISSUE THREAD

**Issue by Romakita** [tsedio/tsed#1389]
## Information

Add [Prisma](https://www.prisma.io/) framework support. Prisma has is own models to configure the table and relations. The idea is to provide a generator embed to the new package `@tsed/prisma` and generate classes and enums based on the `schema.prisma` configuration. The generated classes/enums could be used with the Controllers to generate the Swagger documentation.

Sponsor this feature: https://github.com/sponsors/Romakita?frequency=one-time&sponsor=Romakita

**Currently balance**: 15/15 one-time

[<img width="355" alt="Capture d’écran 2021-05-22 à 09 47 13" src="https://user-images.githubusercontent.com/1763311/119218827-b828f800-bae2-11eb-9517-f502d389cd86.png">](https://github.com/sponsors/Romakita/sponsorships?sponsor=Romakita&tier_id=69644&preview=false)

## Roadmap

- [x] Generate models
- [x] Generate enums
- [x] Generate PrismaService (https://github.com/tsedio/tsed/issues/1402)
- [x] Generate Repository (https://github.com/tsedio/tsed/issues/1402) 

## Example

Prisma configuration:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
}

generator tsed {
  provider = "@tsedio/prisma"
}

model User {
  /// @TsED.Groups("!creation")
  /// Comment
  id          Int      @id @default(autoincrement())
  createdAt   DateTime @default(now())
  /// @TsED.Email()
  /// @TsED.Description("User email. This email must be unique!")
  email       String   @unique
  weight      Float?
  is18        Boolean?
  name        String?
  successorId Int?
  successor   User?    @relation("BlogOwnerHistory", fields: [successorId], references: [id])
  predecessor User?    @relation("BlogOwnerHistory")
  role        Role     @default(USER)
  posts       Post[]
  keywords    String[]
  biography   Json
}

model Post {
  id     Int   @id @default(autoincrement())
  user   User? @relation(fields: [userId], references: [id])
  userId Int?
}

enum Role {
  USER
  ADMIN
}
```
Then run the command to generates files:

```
npx prisma generate
```

<img width="717" alt="Capture d’écran 2021-05-11 à 08 09 40" src="https://user-images.githubusercontent.com/1763311/117766747-563dd800-b230-11eb-8c29-50ba211ddc2b.png">

Outputs:

```typescript
import { User } from "../client";
import { Integer, Required, Property, Groups, Format, Email, Description, Allow, Enum, CollectionOf } from "@tsed/schema";
import { Role } from "../enums";
import { PostModel } from "./PostModel";

export class UserModel implements User {
  @Property(Number)
  @Integer()
  @Required()
  @Groups("!creation")
  id: number;

  @Property(Date)
  @Format("date-time")
  @Required()
  createdAt: Date;

  @Property(String)
  @Required()
  @Email()
  @Description("User email. This email must be unique!")
  email: string;

  @Property(Number)
  @Allow(null)
  weight: number | null;

  @Property(Boolean)
  @Allow(null)
  is18: boolean | null;

  @Property(String)
  @Allow(null)
  name: string | null;

  @Property(Number)
  @Integer()
  @Allow(null)
  successorId: number | null;

  @Property(() => UserModel)
  @Allow(null)
  predecessor: UserModel | null;

  @Required()
  @Enum(Role)
  role: Role;

  @CollectionOf(() => PostModel)
  @Required()
  posts: PostModel[];

  @CollectionOf(String)
  @Required()
  keywords: string[];

  @Property(Object)
  @Required()
  biography: any;
}
```

And, the following repository:

```typescript
import { isArray } from "@tsed/core";
import { deserialize } from "@tsed/json-mapper";
import { Injectable, Inject } from "@tsed/di";
import { PrismaService } from "../services/PrismaService";
import { Prisma, User } from "../client";
import { UserModel } from "../models";

@Injectable()
export class UsersRepository {
  @Inject()
  protected prisma: PrismaService;

  get collection() {
    return this.prisma.user
  }

  get groupBy() {
    return this.collection.groupBy.bind(this.collection)
  }

  protected deserialize<T>(obj: null | User | User[]): T {
    return deserialize<T>(obj, { type: UserModel, collectionType: isArray(obj) ? Array : undefined })
  }

  async findUnique(args: Prisma.UserFindUniqueArgs): Promise<UserModel | null> {
    const obj = await this.collection.findUnique(args);
    return this.deserialize<UserModel | null>(obj);
  }

  async findFirst(args: Prisma.UserFindFirstArgs): Promise<UserModel | null> {
    const obj = await this.collection.findFirst(args);
    return this.deserialize<UserModel | null>(obj);
  }

  async findMany(args?: Prisma.UserFindManyArgs): Promise<UserModel[]> {
    const obj = await this.collection.findMany(args);
    return this.deserialize<UserModel[]>(obj);
  }

  async create(args: Prisma.UserCreateArgs): Promise<UserModel> {
    const obj = await this.collection.create(args);
    return this.deserialize<UserModel>(obj);
  }

  async update(args: Prisma.UserUpdateArgs): Promise<UserModel> {
    const obj = await this.collection.update(args);
    return this.deserialize<UserModel>(obj);
  }

  async upsert(args: Prisma.UserUpsertArgs): Promise<UserModel> {
    const obj = await this.collection.upsert(args);
    return this.deserialize<UserModel>(obj);
  }

  async delete(args: Prisma.UserDeleteArgs): Promise<UserModel> {
    const obj = await this.collection.delete(args);
    return this.deserialize<UserModel>(obj);
  }

  async deleteMany(args: Prisma.UserDeleteManyArgs) {
    return this.collection.deleteMany(args)
  }

  async updateMany(args: Prisma.UserUpdateManyArgs) {
    return this.collection.updateMany(args)
  }

  async aggregate(args: Prisma.UserAggregateArgs) {
    return this.collection.aggregate(args)
  }
}
```

Usage:

```typescript
import {BodyParams, Controller, Get, Post} from "@tsed/common";
import {Inject} from "@tsed/di";
import {Groups, Returns, Summary} from "@tsed/schema";
import {UserModel, UsersRepository} from "@tsedio/prisma";

@Controller("/users")
export class UsersController {
  @Inject()
  protected service: UsersRepository;

  @Post("/")
  @Summary("Create a new user")
  @Returns(201, UserModel)
  async signupUser(@BodyParams() @Groups("creation") user: UserModel): Promise<UserModel> {
    return this.service.create({data: user});
  }

  @Get("/")
  @Summary("Filter posts by title or content")
  @(Returns(200, Array).Of(UserModel).Description("Return a list of User"))
  getAll() {
    return this.service.findMany();
  }
}
```

## Acceptance criteria

- [x] The package generate the classes and enums
- [x] The classes / enums can be imported from @tsed/prisma
- [x] Ts.ED decorators like Groups can be used in the `schema.prisma`
- [x] Documentation is available on tsed.io
- [x] The sponsor goal is reach ! (15 one-time sponsors or 5 monthly sponsors, see capture above). Your help is welcome!

**Comment by Romakita** [comment]
Results:
<img width="1432" alt="Capture d’écran 2021-05-20 à 09 03 22" src="https://user-images.githubusercontent.com/1763311/118934093-40c06080-b94a-11eb-87cf-3c9e8b6f7075.png">

**Comment by Romakita** [comment]
Support of Repositories generation is ready:
<img width="730" alt="Capture d’écran 2021-05-23 à 15 08 43" src="https://user-images.githubusercontent.com/1763311/119262176-9317b080-bbda-11eb-8fa1-4dd618ea4a4f.png">

**Comment by Romakita** [comment]
<img width="661" alt="Capture d’écran 2021-05-23 à 16 05 43" src="https://user-images.githubusercontent.com/1763311/119266029-68812400-bbe9-11eb-84a8-abdc5f75973d.png">

**Comment by Romakita** [comment]
The goal is reached. Prisma module will be released in open-source!!

Thanks to all sponsors! Sponsors will keep his advantage on the support priority on this plugin ;)
