### ISSUE TITLE
[EPIC] Support fastify

### ISSUE THREAD

**Issue by Romakita** [tsedio/tsed#932]
## Informations

The goal is to provide a `@tsed/platform-fastify` package to support Fastify.

Take as example the `@tsed/platform-express` and `@tsed/platform-koa` as examples:
https://github.com/TypedProject/tsed/tree/alpha/packages/platform-express
https://github.com/TypedProject/tsed/tree/alpha/packages/platform-koa

## Tasks

- [x] Create the fastify package (PR #2437)
- [x] Remove all koa reference inside the fastify package (source files and tests files) (Issue: #2445, PR: #)
- [x] Map Fastify Response to PlatformFastifyResponse (Issue: #2446, PR: #)
- [x] Map Fastify Request fo PlatformFastifyRequest (Issue: #2447, PR: #)
- [x] Implement the `mapHandler()` method in PlatformFastify (Issue: #2451, PR: # )
- [x] Implement the `mapLayers()` method in PlatformFastify (Issue: #2452, PR: # )
- [x] Implement the `useRouter()` method in PlatformFastify (Issue: #, PR: # )
- [x] Implement the `multipart()` method  in PlatformFastify (Issue: #, PR: # )
- [x] Implement the `statics()` method  in PlatformFastify (Issue: #, PR: # )
- [x] Add documentation section on the website (PR: https://github.com/tsedio/tsed/pull/3039)
   - [x] Home page reference the Fastify page
   - [x] Add a new page on fastify platform
   - [x] Capability table is up to date: https://tsed.io/getting-started/

Board:
https://github.com/orgs/tsedio/projects/4/views/1

All Fastify related issues:
https://github.com/tsedio/tsed/issues?q=is%3Aopen+is%3Aissue+label%3AFastify

## Acceptance criteria

- [x] Ts.ED server start on Fastify
- [x] All integration test works

**Comment by vincent-thomas** [comment]
Fighting with the stale bot? Haha

**Comment by Romakita** [comment]
Yes ^^. I haven’t started this feature, but it’s a goal ^^

**Comment by vincent-thomas** [comment]
It would be awesome if this framework could support fastify! I'm thinking of using this framework instead of nestjs. Leaning against tsed ☺️

**Comment by vibh1103** [comment]
Hi @Romakita,
Can i pick this task ?

**Comment by Romakita** [comment]
Hum, the PR is already started here: 
https://github.com/tsedio/tsed/pull/2437
But no time to continu the dev :)

**Comment by vibh1103** [comment]
Thanks for update is there any other task I'll pick ?

**Comment by Romakita** [comment]
Hello @vibh1103 
You help on this enhancement is welcome!
We can work together on this PR ;). We can split the issue in subtasks like this:

- Remove all koa reference inside the fastify package (source files and tests files) (PR #)
- Map Fastify Response to PlatformFastifyResponse (PR #)
- Map Fastify Request fo PlatformFastifyRequest (PR #)
- Implement the `mapHandler()` method in PlatformFastify (PR # )
- Implement the `mapLayers()` method in PlatformFastify (PR # )
- Implement the `useRouter()` method in PlatformFastify (PR # )
- Implement the `multipart()` method  in PlatformFastify (PR # )
- Implement the `statics()` method  in PlatformFastify (PR # )

> Note: I added theses tasks on the first message on this story

You can make small PR for each tasks ;). It will me help a lot :). If you have any question. Tell me!

See you

**Comment by Romakita** [comment]
`@tsed/cli` v6.2.0-beta.2 can generate a fastify project


```sh
npm i -g @tsed/cli@6.2.0-beta.2
tsed init . --tsed-version 8.5.0-beta.2
```

<img width="419" alt="Image" src="https://github.com/user-attachments/assets/28f625f6-0d82-4371-bec4-41e17c20d6fc" />

<img width="944" alt="Image" src="https://github.com/user-attachments/assets/ff0654cd-14c6-4f91-8791-d74b0d535a2f" />
